export {
  appointmentListQuerySchema,
  appointmentReferenceSchema,
  appointmentSchema,
  appointmentScopeSchema,
  appointmentStatusSchema,
  bookGuestAppointmentRequestSchema,
  bookGuestAppointmentRequestSchemaFor,
  bookedAppointmentSchema,
  cancelAppointmentRequestSchema,
  cancellationActorSchema,
  changeAppointmentStatusRequestSchema,
  citedAppointmentReferenceSchema,
  createAppointmentRequestSchema,
  dataConsentSchema,
  DEFAULT_APPOINTMENT_SCOPE,
  guestContactSchema,
  guestContactSchemaFor,
  MY_APPOINTMENTS_DEFAULT_LIMIT,
  MY_APPOINTMENTS_MAX_LIMIT,
  myAppointmentsQuerySchema,
  receivedAppointmentStatusSchema,
  receivedCancellationActorSchema,
  rescheduleAppointmentRequestSchema,
} from './appointment';
export type {
  Appointment,
  AppointmentListQuery,
  AppointmentReference,
  AppointmentScope,
  BookGuestAppointmentRequest,
  BookedAppointment,
  CancelAppointmentRequest,
  ChangeAppointmentStatusRequest,
  CreateAppointmentRequest,
  GuestContact,
  MyAppointmentsQuery,
  RescheduleAppointmentRequest,
} from './appointment';

export {
  APPOINTMENT_FEED_CHANGES,
  APPOINTMENT_FEED_EVENT,
  APPOINTMENT_FEED_HEARTBEAT,
  appointmentFeedChangeSchema,
  appointmentFeedEventSchema,
} from './appointment-feed';
export type { AppointmentFeedChange, AppointmentFeedEvent } from './appointment-feed';

export {
  availabilityQuerySchema,
  availabilityResponseSchema,
  availabilitySlotSchema,
  closingDaysSchema,
  createStaffTimeOffRequestSchema,
  dayAvailabilitySchema,
  END_OF_DAY_LOCAL_TIME,
  ISO_WEEKDAYS,
  isoWeekdayOf,
  isoWeekdaySchema,
  MAX_STAFF_SCHEDULE_ENTRIES,
  MINUTES_IN_CIVIL_DAY,
  scheduleEndTimeSchema,
  scheduleEndToMinutes,
  setClosingDaysRequestSchema,
  setStaffScheduleRequestSchema,
  staffBusyIntervalSchema,
  staffScheduleEntriesOverlap,
  staffScheduleEntrySchema,
  staffScheduleSchema,
  staffTimeOffQuerySchema,
  staffTimeOffSchema,
  updateStaffTimeOffRequestSchema,
} from './availability';
export type {
  AvailabilityQuery,
  AvailabilityResponse,
  AvailabilitySlot,
  ClosingDays,
  CreateStaffTimeOffRequest,
  DayAvailability,
  IsoWeekday,
  ScheduleEndTime,
  SetClosingDaysRequest,
  SetStaffScheduleRequest,
  StaffBusyInterval,
  StaffSchedule,
  StaffScheduleEntry,
  StaffTimeOff,
  StaffTimeOffQuery,
  UpdateStaffTimeOffRequest,
} from './availability';

export {
  assignServiceStaffRequestSchema,
  bufferMinutesSchema,
  createServiceCategoryRequestSchema,
  createServiceRequestSchema,
  createStaffMemberRequestSchema,
  publicServiceSchema,
  serviceCategorySchema,
  serviceCategorySummarySchema,
  serviceSchema,
  serviceStaffMemberSchema,
  serviceSummarySchema,
  setStaffServicesRequestSchema,
  staffMemberSchema,
  staffMemberSummarySchema,
  updateServiceCategoryRequestSchema,
  updateServiceRequestSchema,
  updateStaffMemberRequestSchema,
} from './catalog';
export type {
  AssignServiceStaffRequest,
  CreateServiceCategoryRequest,
  CreateServiceRequest,
  CreateStaffMemberRequest,
  PublicService,
  Service,
  ServiceCategory,
  ServiceCategorySummary,
  ServiceStaffMember,
  ServiceSummary,
  SetStaffServicesRequest,
  StaffMember,
  StaffMemberSummary,
  UpdateServiceCategoryRequest,
  UpdateServiceRequest,
  UpdateStaffMemberRequest,
} from './catalog';

export {
  billingRedirectSchema,
  isBillingOpen,
  SUBSCRIPTION_PLAN,
  TENANT_BILLING_STATUSES,
  tenantBillingSchema,
  tenantBillingStatusSchema,
} from './billing';
export type { BillingRedirect, TenantBilling, TenantBillingStatus } from './billing';

export { salonSignupRequestSchema } from './signup';
export type { SalonSignupRequest } from './signup';

export {
  createCustomerRequestSchema,
  customerHistoryQuerySchema,
  customerPageSchema,
  customerSchema,
  customerSearchQuerySchema,
  customerSummarySchema,
  customerVisitHistorySchema,
  customerVisitSchema,
  customerVisitSummarySchema,
  CUSTOMER_HISTORY_MAX_VISITS,
  CUSTOMER_SEARCH_MAX_LENGTH,
  CUSTOMER_SEARCH_MIN_LENGTH,
  emailSuppressionReasonSchema,
  EMAIL_SUPPRESSION_REASONS,
  receivedEmailSuppressionReasonSchema,
  setCustomerStatusRequestSchema,
  updateCustomerRequestSchema,
} from './crm';
export type {
  CreateCustomerRequest,
  Customer,
  CustomerHistoryQuery,
  CustomerPage,
  CustomerSearchQuery,
  CustomerSummary,
  CustomerVisit,
  CustomerVisitHistory,
  CustomerVisitSummary,
  EmailSuppressionReason,
  SetCustomerStatusRequest,
  UpdateCustomerRequest,
} from './crm';

export {
  acceptInvitationRequestSchema,
  accountDataConsentSchema,
  authSessionResponseSchema,
  authSessionSchema,
  authTokensSchema,
  authenticatedAccountSchema,
  changePasswordRequestSchema,
  createStaffAccountRequestSchema,
  loginRequestSchema,
  passwordResetConfirmRequestSchema,
  passwordResetRequestSchema,
  permissionSchema,
  receivedUserRoleSchema,
  refreshTokenRequestSchema,
  registerRequestSchema,
  sessionUserSchema,
  staffAccountStateSchema,
  tenantScopedLoginRequestSchema,
  tenantScopedRegisterRequestSchema,
  updateProfileRequestSchema,
  userRoleSchema,
  userSchema,
  userSummarySchema,
} from './identity';
export type {
  AcceptInvitationRequest,
  AuthSession,
  AuthSessionResponse,
  AuthTokens,
  AuthenticatedAccount,
  ChangePasswordRequest,
  CreateStaffAccountRequest,
  LoginRequest,
  PasswordResetConfirmRequest,
  PasswordResetRequest,
  RefreshTokenRequest,
  RegisterRequest,
  SessionUser,
  StaffAccountState,
  TenantScopedLoginRequest,
  TenantScopedRegisterRequest,
  UpdateProfileRequest,
  User,
  UserSummary,
} from './identity';

export {
  notificationChannelSchema,
  notificationListQuerySchema,
  notificationPreferencesSchema,
  notificationSchema,
  notificationStatusSchema,
  notificationTypeSchema,
} from './notification';
export type {
  Notification,
  NotificationListQuery,
  NotificationPreferences,
} from './notification';

export {
  createPlatformNoteRequestSchema,
  createTenantRequestSchema,
  PLATFORM_ACCOUNT_ROLES,
  PLATFORM_NOTE_MAX_LENGTH,
  PLATFORM_PASSWORD_MAX_LENGTH,
  PLATFORM_PASSWORD_MIN_LENGTH,
  PLATFORM_STATUS_REASON_MAX_LENGTH,
  PLATFORM_STATUS_REASON_MIN_LENGTH,
  PLATFORM_TENANT_EVENT_KINDS,
  PLATFORM_TENANT_ORIGINS,
  PLATFORM_TENANT_SEARCH_MAX_LENGTH,
  PLATFORM_TENANT_STATES,
  platformLoginRequestSchema,
  platformOperatorSchema,
  platformOverviewSchema,
  platformSessionSchema,
  platformSignupWeekSchema,
  platformTenantAccountSchema,
  platformTenantActivitySchema,
  platformTenantDetailSchema,
  platformTenantEventKindSchema,
  platformTenantEventSchema,
  platformTenantListQuerySchema,
  platformTenantOriginSchema,
  platformTenantPageSchema,
  platformTenantSchema,
  platformTenantSetupSchema,
  platformTenantStateSchema,
  provisionedTenantSchema,
  reissuedTenantInvitationSchema,
  tenantAccessLinksSchema,
  updateTenantStatusRequestSchema,
} from './platform';
export type {
  CreatePlatformNoteRequest,
  CreateTenantRequest,
  PlatformLoginRequest,
  PlatformOperator,
  PlatformOverview,
  PlatformSession,
  PlatformSignupWeek,
  PlatformTenant,
  PlatformTenantAccount,
  PlatformTenantActivity,
  PlatformTenantDetail,
  PlatformTenantEvent,
  PlatformTenantEventKind,
  PlatformTenantListQuery,
  PlatformTenantOrigin,
  PlatformTenantPage,
  PlatformTenantSetup,
  PlatformTenantState,
  ProvisionedTenant,
  ReissuedTenantInvitation,
  TenantAccessLinks,
  UpdateTenantStatusRequest,
} from './platform';

export {
  counterPaymentMethodSchema,
  createPaymentIntentRequestSchema,
  paymentIntentSchema,
  paymentListQuerySchema,
  paymentMethodSchema,
  paymentSchema,
  paymentStatusSchema,
  recordCounterPaymentRequestSchema,
  refundPaymentRequestSchema,
  saleSettlementSchema,
  settleSaleRequestSchema,
} from './payment';
export type {
  CounterPaymentMethod,
  CreatePaymentIntentRequest,
  Payment,
  PaymentIntent,
  PaymentListQuery,
  RecordCounterPaymentRequest,
  RefundPaymentRequest,
  SaleSettlement,
  SettleSaleRequest,
} from './payment';

// Les cinq schémas d'identité légale sont réexportés depuis `./tenant`, où ils
// vivent depuis #913 — ce sont des colonnes de `tenants`. Les nommer ici sous
// leur module d'origine aurait fait croire que le reçu les possède.
export {
  receiptIssuerSchema,
  receiptLineKindSchema,
  receiptLineSchema,
  receiptPartySchema,
  receiptRefundSchema,
  receiptSettlementSchema,
  receiptTaxLineSchema,
  saleReceiptSchema,
} from './receipt';
export type {
  ReceiptIssuer,
  ReceiptLine,
  ReceiptParty,
  ReceiptRefund,
  ReceiptSettlement,
  ReceiptTaxLine,
  SaleReceipt,
} from './receipt';

export { MAX_REPORT_EXPORT_TTL_SECONDS, reportExportSchema } from './reporting';
export type { ReportExport } from './reporting';

export {
  myStaffAgendaSchema,
  myStaffAppointmentClientSchema,
  myStaffAppointmentSchema,
  myStaffProfileSchema,
  myStaffRangeQuerySchema,
  myStaffScheduleSchema,
  UTC_OFFSET_MINUTES_MAX,
  UTC_OFFSET_MINUTES_MIN,
} from './staff-portal';
export type {
  MyStaffAgenda,
  MyStaffAppointment,
  MyStaffAppointmentClient,
  MyStaffProfile,
  MyStaffRangeQuery,
  MyStaffSchedule,
} from './staff-portal';

export {
  legalIdSchema,
  legalIdTypeSchema,
  legalNameSchema,
  openingHoursEntrySchema,
  openingHoursOverlap,
  openingHoursSchema,
  postalAddressSchema,
  publicTenantSchema,
  receiptFooterSchema,
  receiptPrefixSchema,
  sortOpeningHours,
  taxRateBpsSchema,
  tenantBookingSettingsSchema,
  tenantSchema,
  updateTenantRequestSchema,
  vatNumberSchema,
} from './tenant';
export type {
  OpeningHoursEntry,
  PostalAddress,
  PublicTenant,
  Tenant,
  TenantBookingSettings,
  UpdateTenantRequest,
} from './tenant';
